# Generated by Django 4.1 on 2024-08-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("producer_country_name", models.CharField(max_length=100)),
                ("is_visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="parts.mark",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("json_data", models.JSONField(blank=True, default=dict)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="parts.mark",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="parts.model",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(fields=["name"], name="parts_mark_name_c18acd_idx"),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(
                fields=["producer_country_name"], name="parts_mark_produce_0c7cce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(fields=["name"], name="parts_part_name_c99d7b_idx"),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(fields=["price"], name="parts_part_price_ee5bf7_idx"),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["is_visible"], name="parts_part_is_visi_b97efa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="model",
            index=models.Index(fields=["name"], name="parts_model_name_cededa_idx"),
        ),
    ]
